--------------------------------------------------------
-- Archivo creado  - lunes-mayo-27-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "CUSTOMER_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DOCUMENT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "DOCUMENT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OWNER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OWNER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OWNER_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "OWNER_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_FORM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAYMENT_FORM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_FORM_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PAYMENT_FORM_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PROPERTY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PROPERTY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PROPERTY_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "PROPERTY_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RENT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "RENT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"NDI" VARCHAR2(10 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "DOCUMENT" 
   (	"ID" NUMBER(*,0), 
	"PATH" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PROPERTY_ID" NUMBER(*,0), 
	"PROPERTY_OWNER_ID" NUMBER(*,0), 
	"RENT_ID" NUMBER(*,0), 
	"RENT_PROPERTY_ID" NUMBER(*,0), 
	"RENT_PROPERTY_OWNER_ID" NUMBER(*,0), 
	"RENT_CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table OWNER
--------------------------------------------------------

  CREATE TABLE "OWNER" 
   (	"ID" NUMBER(*,0), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"NDI" VARCHAR2(10 BYTE), 
	"CORREO" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table PAYMENT_FORM
--------------------------------------------------------

  CREATE TABLE "PAYMENT_FORM" 
   (	"ID" NUMBER(*,0), 
	"TYPE_CREDIT_CARD" VARCHAR2(10 BYTE), 
	"CREDIT_CARD_NUMBER" VARCHAR2(20 BYTE), 
	"NAME_HOLDER" VARCHAR2(50 BYTE), 
	"EXPIRY_DATE" DATE, 
	"CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table PROPERTY
--------------------------------------------------------

  CREATE TABLE "PROPERTY" 
   (	"ID" NUMBER(*,0), 
	"TYPE" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"ROOMS_NUMBER" NUMBER(*,0), 
	"RENT" NUMBER(10,2), 
	"OWNER_ID" NUMBER(*,0), 
	"LOCATION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table RENT
--------------------------------------------------------

  CREATE TABLE "RENT" 
   (	"ID" NUMBER(*,0), 
	"RENTAL_DATE" DATE, 
	"RENTAL_TIME_START" DATE, 
	"RENTAL_TIME_END" DATE, 
	"RENT_PROPERTY" NUMBER(10,2), 
	"STATE" NUMBER(*,0), 
	"PROPERTY_ID" NUMBER(*,0), 
	"PROPERTY_OWNER_ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Table VISITING_LIST
--------------------------------------------------------

  CREATE TABLE "VISITING_LIST" 
   (	"STATE" NUMBER(*,0), 
	"PROPERTY_ID" NUMBER(*,0), 
	"PROPERTY_OWNER_ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "ESTUDIANTES" ;
REM INSERTING into CUSTOMER
SET DEFINE OFF;
Insert into CUSTOMER (ID,NAME,LAST_NAME,NDI,CORREO,USERNAME,PASSWORD) values ('1','Charles','Barón','1059638459','charles@mail.com','charlesito','c123');
Insert into CUSTOMER (ID,NAME,LAST_NAME,NDI,CORREO,USERNAME,PASSWORD) values ('2','Cock','Cuchimba','1032426924','cockito@mail.com','cockito','co123');
Insert into CUSTOMER (ID,NAME,LAST_NAME,NDI,CORREO,USERNAME,PASSWORD) values ('3','Pabli','Ariza','7896341028','pabli@mail.com','pablis','p123');
REM INSERTING into DOCUMENT
SET DEFINE OFF;
Insert into DOCUMENT (ID,PATH,NAME,PROPERTY_ID,PROPERTY_OWNER_ID,RENT_ID,RENT_PROPERTY_ID,RENT_PROPERTY_OWNER_ID,RENT_CUSTOMER_ID) values ('1','https://conceptodefinicion.de/wp-content/uploads/2017/12/Apartamento.jpg','Apto Chau','1','1','1','1','1','1');
Insert into DOCUMENT (ID,PATH,NAME,PROPERTY_ID,PROPERTY_OWNER_ID,RENT_ID,RENT_PROPERTY_ID,RENT_PROPERTY_OWNER_ID,RENT_CUSTOMER_ID) values ('2','https://conceptodefinicion.de/wp-content/uploads/2017/12/Apartamento.jpg','Apto Chau 1','1',null,null,null,null,null);
REM INSERTING into OWNER
SET DEFINE OFF;
Insert into OWNER (ID,LAST_NAME,NAME,NDI,CORREO,USERNAME,PASSWORD) values ('1','Chaustre','Santi','1034987652','santi@mail.com','chau','s123');
Insert into OWNER (ID,LAST_NAME,NAME,NDI,CORREO,USERNAME,PASSWORD) values ('2','Rojas','Ailin','1045923617','ailin@mail.com','ailinrb','a123');
REM INSERTING into PAYMENT_FORM
SET DEFINE OFF;
REM INSERTING into PROPERTY
SET DEFINE OFF;
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('1','1','Carrera 7 # 42-65','2','16,01','1','kennedy');
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('3','2','Calle 63 # 20-06','4','240','2','palermo');
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('4','1','Tv 5 #42-34','1','160','1','chapigay');
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('2','2','Calle 11#24-23','5','300','1','CalleVieja');
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('5','2','Carrer 93#76-2','1','10','2','Nordelta');
Insert into PROPERTY (ID,TYPE,ADDRESS,ROOMS_NUMBER,RENT,OWNER_ID,LOCATION) values ('6','1','Calle 1#2-3','3','78','2','MarDelPlata');
REM INSERTING into RENT
SET DEFINE OFF;
Insert into RENT (ID,RENTAL_DATE,RENTAL_TIME_START,RENTAL_TIME_END,RENT_PROPERTY,STATE,PROPERTY_ID,PROPERTY_OWNER_ID,CUSTOMER_ID) values ('1',to_date('21/05/19','DD/MM/RR'),to_date('30/05/19','DD/MM/RR'),to_date('30/05/20','DD/MM/RR'),'16,01','1','1','1','1');
REM INSERTING into VISITING_LIST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_PK" ON "CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index DOCUMENT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOCUMENT_PK1" ON "DOCUMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index OWNER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OWNER_PK" ON "OWNER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_FORM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAYMENT_FORM_PK" ON "PAYMENT_FORM" ("ID", "CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index PROPERTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROPERTY_PK" ON "PROPERTY" ("ID", "OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index RENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENT_PK" ON "RENT" ("ID", "PROPERTY_ID", "PROPERTY_OWNER_ID", "CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Index VISITING_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VISITING_LIST_PK" ON "VISITING_LIST" ("PROPERTY_ID", "PROPERTY_OWNER_ID", "CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ESTUDIANTES" ;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CUSTOMER_TRG" 
BEFORE INSERT ON CUSTOMER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CUSTOMER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOCUMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DOCUMENT_TRG" 
BEFORE INSERT ON DOCUMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DOCUMENT_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DOCUMENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OWNER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "OWNER_TRG" 
BEFORE INSERT ON OWNER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "OWNER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAYMENT_FORM_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAYMENT_FORM_TRG" 
BEFORE INSERT ON PAYMENT_FORM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PAYMENT_FORM_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PAYMENT_FORM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROPERTY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROPERTY_TRG" 
BEFORE INSERT ON PROPERTY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROPERTY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROPERTY_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROPERTY_TRG1" 
BEFORE INSERT ON PROPERTY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PROPERTY_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PROPERTY_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "RENT_TRG" 
BEFORE INSERT ON RENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT RENT_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "RENT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT_FORM
--------------------------------------------------------

  ALTER TABLE "PAYMENT_FORM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PAYMENT_FORM" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "PAYMENT_FORM" ADD CONSTRAINT "PAYMENT_FORM_PK" PRIMARY KEY ("ID", "CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "DOCUMENT_PK1" ON "DOCUMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table OWNER
--------------------------------------------------------

  ALTER TABLE "OWNER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OWNER" ADD CONSTRAINT "OWNER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VISITING_LIST
--------------------------------------------------------

  ALTER TABLE "VISITING_LIST" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "VISITING_LIST" MODIFY ("PROPERTY_OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "VISITING_LIST" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "VISITING_LIST" ADD CONSTRAINT "VISITING_LIST_PK" PRIMARY KEY ("PROPERTY_ID", "PROPERTY_OWNER_ID", "CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "PROPERTY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("ROOMS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("RENT" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "PROPERTY" ADD CONSTRAINT "PROPERTY_PK" PRIMARY KEY ("ID", "OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENT
--------------------------------------------------------

  ALTER TABLE "RENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RENT" MODIFY ("PROPERTY_ID" NOT NULL ENABLE);
  ALTER TABLE "RENT" MODIFY ("PROPERTY_OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "RENT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "RENT" ADD CONSTRAINT "RENT_PK" PRIMARY KEY ("ID", "PROPERTY_ID", "PROPERTY_OWNER_ID", "CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ESTUDIANTES"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_PROPERTY_FK" FOREIGN KEY ("PROPERTY_ID", "PROPERTY_OWNER_ID")
	  REFERENCES "PROPERTY" ("ID", "OWNER_ID") ENABLE;
  ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_RENT_FK" FOREIGN KEY ("RENT_ID", "RENT_PROPERTY_ID", "RENT_PROPERTY_OWNER_ID", "RENT_CUSTOMER_ID")
	  REFERENCES "RENT" ("ID", "PROPERTY_ID", "PROPERTY_OWNER_ID", "CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_FORM
--------------------------------------------------------

  ALTER TABLE "PAYMENT_FORM" ADD CONSTRAINT "PAYMENT_FORM_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "PROPERTY" ADD CONSTRAINT "PROPERTY_OWNER_FK" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "OWNER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENT
--------------------------------------------------------

  ALTER TABLE "RENT" ADD CONSTRAINT "RENT_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "RENT" ADD CONSTRAINT "RENT_PROPERTY_FK" FOREIGN KEY ("PROPERTY_ID", "PROPERTY_OWNER_ID")
	  REFERENCES "PROPERTY" ("ID", "OWNER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITING_LIST
--------------------------------------------------------

  ALTER TABLE "VISITING_LIST" ADD CONSTRAINT "VISITING_LIST_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "VISITING_LIST" ADD CONSTRAINT "VISITING_LIST_PROPERTY_FK" FOREIGN KEY ("PROPERTY_ID", "PROPERTY_OWNER_ID")
	  REFERENCES "PROPERTY" ("ID", "OWNER_ID") ENABLE;
